theme: minima
title: My blog
description: My very nice blog
author: "Sher Lynn Wong"
logo: /assets/logo/profile.png

github_username: sherlynnw
linkedin_username: sher-lynn-wong

header_pages:
  - index.md
  - aboutme.md
  - professional.md
  - undergraduate.md
  - volunteering.md
