theme: minima

title: Sher Lynn Wong (She/Her)
description: Hi there! I'm Sher Lynn, a self-taught Data Science & Machine Learning Engineer based in London. I have delivered multiple projects through the Software Development Lifecycle and have worked with technical and non-technical stakeholders. I am a self-starter and work best in fast-paced environments.
logo: /assets/logo/profile.png

github_username: sherlynnw
linkedin_username: sher-lynn-wong

header_pages:
  - index.md
  - test.md
  - _professional/index.md

include:
  - _professional
