theme: jekyll-theme-minimal
title: Sher Lynn Wong (She/Her)
description: Hi there! I'm Sher Lynn, a Data Science & Machine Learning Engineer. I am a Civil Engineering graduate from Imperial College London.
logo: /assets/logo/profile.png
